name: CI

on:
  push:
    branches:
      - "master"
    tags:
      - v*
  pull_request:
    branches:
      - "master"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Lint
        run: make lint

      - name: Test
        run: make test

  build:
    name: Build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: build cross
        run: make cross

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: built_binaries
          path: cmd/build

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - test
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: built_binaries
          path: cmd/build

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref_name }}
          artifacts: cmd/build/*
